console.log("Conectado");
const datos = {
  bienes: [
    {
      nombre: "Tu perfecto hogar",
      categoria: "Casa",
      imagen: "imagen.jpg",
      codigo: 1234,
      precio: 60000000,
      ubicacion: "Cali",
      area: "75 m2",
      detalles: "Buena ubicacion, excelente vista",
    },
    {
      nombre: "Casa Colonial",
      categoria: "Casa",
      imagen: "casa_colonial.jpg",
      codigo: 1008,
      precio: 180000000,
      ubicacion: "Cartagena",
      area: "180 m2",
      detalles:
        "Casa histórica restaurada, con detalles arquitectónicos únicos y patio interior.",
    },
    {
      nombre: "Apartamento de Lujo",
      categoria: "Apartamento",
      imagen: "apartamento_lujo.jpg",
      codigo: 1009,
      precio: 900000000,
      ubicacion: "Bogotá",
      area: "300 m2",
      detalles:
        "Espectacular apartamento de alto standing con acabados de primera calidad y vistas panorámicas.",
    },
    {
      nombre: "Finca Ganadera",
      categoria: "Finca",
      imagen: "finca_ganadera.jpg",
      codigo: 1010,
      precio: 1200000000,
      ubicacion: "Antioquia",
      area: "500 ha",
      detalles:
        "Finca productiva con instalaciones para ganado, cultivos y agua propia.",
    },
    {
      nombre: "Edificio de Oficinas",
      categoria: "Edificio",
      imagen: "edificio_oficinas.jpg",
      codigo: 1011,
      precio: 5000000000,
      ubicacion: "Medellín",
      area: "2000 m2",
      detalles:
        "Edificio corporativo con múltiples niveles, estacionamiento y acceso a servicios empresariales.",
    },
    {
      nombre: "Casa Campestre",
      categoria: "Casa",
      imagen: "casa_campestre.jpg",
      codigo: 1012,
      precio: 350000000,
      ubicacion: "Cundinamarca",
      area: "250 m2",
      detalles:
        "Casa en entorno natural con amplias áreas verdes y espacios para el esparcimiento familiar.",
    },
    {
      nombre: "Local Comercial en Centro Comercial",
      categoria: "Local",
      imagen: "local_comercial_centro_comercial.jpg",
      codigo: 1013,
      precio: 500000000,
      ubicacion: "Bogotá",
      area: "150 m2",
      detalles:
        "Local estratégicamente ubicado dentro de un reconocido centro comercial, con alto tráfico de clientes.",
    },
    {
      nombre: "Terreno Industrial",
      categoria: "Terreno",
      imagen: "terreno_industrial.jpg",
      codigo: 1014,
      precio: 800000000,
      ubicacion: "Valle del Cauca",
      area: "1000 m2",
      detalles:
        "Terreno apto para desarrollo industrial, con acceso a servicios básicos y buena conectividad.",
    },
    {
      nombre: "Casa de Playa",
      categoria: "Casa",
      imagen: "casa_playa.jpg",
      codigo: 1015,
      precio: 600000000,
      ubicacion: "Santa Marta",
      area: "200 m2",
      detalles:
        "Casa junto al mar con acceso directo a la playa, ideal para vacaciones y descanso.",
    },
    {
      nombre: "Apartamento Ejecutivo",
      categoria: "Apartamento",
      imagen: "apartamento_ejecutivo.jpg",
      codigo: 1016,
      precio: 450000000,
      ubicacion: "Cali",
      area: "150 m2",
      detalles:
        "Apartamento moderno y funcional en zona residencial exclusiva, con servicios cercanos.",
    },
    {
      nombre: "Hotel Boutique",
      categoria: "Hotel",
      imagen: "hotel_boutique.jpg",
      codigo: 1017,
      precio: 3500000000,
      ubicacion: "Cartagena",
      area: "1000 m2",
      detalles:
        "Hotel boutique de lujo con diseño único y servicios premium, ubicado en el casco histórico.",
    },
    {
      nombre: "Edificio Residencial",
      categoria: "Edificio",
      imagen: "edificio_residencial.jpg",
      codigo: 1018,
      precio: 10000000000,
      ubicacion: "Bogotá",
      area: "5000 m2",
      detalles:
        "Edificio de apartamentos de alta gama con áreas comunes, gimnasio y seguridad 24 horas.",
    },
    {
      nombre: "Local en Zona Comercial",
      categoria: "Local",
      imagen: "local_zona_comercial.jpg",
      codigo: 1019,
      precio: 300000000,
      ubicacion: "Medellín",
      area: "80 m2",
      detalles:
        "Local en zona comercial de alto tráfico, ideal para negocios de retail o servicios.",
    },
    {
      nombre: "Terreno para Desarrollo Residencial",
      categoria: "Terreno",
      imagen: "terreno_desarrollo_residencial.jpg",
      codigo: 1020,
      precio: 2000000000,
      ubicacion: "Cundinamarca",
      area: "10 ha",
      detalles:
        "Terreno para proyecto residencial con estudio de impacto ambiental y planos aprobados.",
    },
    {
      nombre: "Casa Moderna",
      categoria: "Casa",
      imagen: "casa_moderna.jpg",
      codigo: 1021,
      precio: 280000000,
      ubicacion: "Antioquia",
      area: "180 m2",
      detalles:
        "Casa contemporánea con diseño vanguardista y áreas sociales integradas.",
    },
    {
      nombre: "Apartamento en Complejo Residencial",
      categoria: "Apartamento",
      imagen: "apartamento_complejo_residencial.jpg",
      codigo: 1022,
      precio: 550000000,
      ubicacion: "Bogotá",
      area: "150 m2",
      detalles:
        "Apartamento en complejo residencial con áreas verdes, piscina y seguridad.",
    },
    {
      nombre: "Finca de Recreo",
      categoria: "Finca",
      imagen: "finca_recreo.jpg",
      codigo: 1023,
      precio: 700000000,
      ubicacion: "Tolima",
      area: "500 m2",
      detalles:
        "Finca con casa de recreo, zona BBQ, piscina y acceso a ríos y cascadas.",
    },
    {
      nombre: "Edificio Comercial",
      categoria: "Edificio",
      imagen: "edificio_comercial.jpg",
      codigo: 1024,
      precio: 15000000000,
      ubicacion: "Barranquilla",
      area: "8000 m2",
      detalles:
        "Edificio comercial con locales, oficinas y estacionamiento, en área de alto desarrollo empresarial.",
    },

    {
      nombre: "Casa Campestre con Lago Privado",
      categoria: "Casa",
      imagen: "casa_campestre_lago.jpg",
      codigo: 1025,
      precio: 1500000000,
      ubicacion: "Caldas",
      area: "400 m2",
      detalles:
        "Casa campestre con amplios jardines, piscina y lago privado para actividades acuáticas.",
    },
    {
      nombre: "Apartamento con Vista al Mar",
      categoria: "Apartamento",
      imagen: "apartamento_vista_mar.jpg",
      codigo: 1026,
      precio: 900000000,
      ubicacion: "Santa Marta",
      area: "180 m2",
      detalles:
        "Apartamento con terraza y vista panorámica al mar, en exclusivo sector turístico.",
    },
    {
      nombre: "Local en Centro Histórico",
      categoria: "Local",
      imagen: "local_centro_historico.jpg",
      codigo: 1027,
      precio: 400000000,
      ubicacion: "Cartagena",
      area: "120 m2",
      detalles:
        "Local comercial en el corazón del centro histórico, ideal para negocio turístico.",
    },
    {
      nombre: "Terreno Industrial en Parque Empresarial",
      categoria: "Terreno",
      imagen: "terreno_industrial_parque_empresarial.jpg",
      codigo: 1028,
      precio: 1200000000,
      ubicacion: "Cali",
      area: "5000 m2",
      detalles:
        "Terreno en parque empresarial con infraestructura y servicios para industria liviana o logística.",
    },
    {
      nombre: "Casa de Playa con Piscina Privada",
      categoria: "Casa",
      imagen: "casa_playa_piscina.jpg",
      codigo: 1029,
      precio: 1200000000,
      ubicacion: "Santa Marta",
      area: "300 m2",
      detalles:
        "Casa junto al mar con piscina privada, terraza y acceso directo a la playa.",
    },
    {
      nombre: "Apartamento de Diseño",
      categoria: "Apartamento",
      imagen: "apartamento_diseno.jpg",
      codigo: 1030,
      precio: 700000000,
      ubicacion: "Bogotá",
      area: "160 m2",
      detalles:
        "Apartamento con diseño interior de vanguardia y espacios funcionales.",
    },
    {
      nombre: "Finca Agrícola",
      categoria: "Finca",
      imagen: "finca_agricola.jpg",
      codigo: 1031,
      precio: 2000000000,
      ubicacion: "Cundinamarca",
      area: "50 ha",
      detalles:
        "Finca con cultivos y maquinaria agrícola, ideal para producción agropecuaria.",
    },
    {
      nombre: "Edificio de Apartaestudios",
      categoria: "Edificio",
      imagen: "edificio_apartaestudios.jpg",
      codigo: 1032,
      precio: 8000000000,
      ubicacion: "Medellín",
      area: "4000 m2",
      detalles:
        "Edificio con apartaestudios amoblados, en zona universitaria y de alta demanda estudiantil.",
    },
    {
      nombre: "Local en Centro Comercial de Lujo",
      categoria: "Local",
      imagen: "local_centro_comercial_lujo.jpg",
      codigo: 1033,
      precio: 600000000,
      ubicacion: "Bogotá",
      area: "200 m2",
      detalles:
        "Local en centro comercial exclusivo, con diseño elegante y alta afluencia de clientes.",
    },
    {
      nombre: "Terreno para Proyecto Residencial",
      categoria: "Terreno",
      imagen: "terreno_proyecto_residencial.jpg",
      codigo: 1034,
      precio: 3500000000,
      ubicacion: "Antioquia",
      area: "20 ha",
      detalles:
        "Terreno con estudio de suelo y planos aprobados para desarrollo de conjunto residencial.",
    },
    {
      nombre: "Casa Rural",
      categoria: "Casa",
      imagen: "casa_rural.jpg",
      codigo: 1035,
      precio: 250000000,
      ubicacion: "Boyacá",
      area: "120 m2",
      detalles:
        "Casa en zona rural con amplio terreno, árboles frutales y clima agradable.",
    },
    {
      nombre: "Apartamento con Terraza Panorámica",
      categoria: "Apartamento",
      imagen: "apartamento_terraza_panoramica.jpg",
      codigo: 1036,
      precio: 600000000,
      ubicacion: "Medellín",
      area: "180 m2",
      detalles:
        "Apartamento con amplia terraza y vista panorámica de la ciudad, en zona exclusiva.",
    },
    {
      nombre: "Local en Centro Financiero",
      categoria: "Local",
      imagen: "local_centro_financiero.jpg",
      codigo: 1037,
      precio: 1500000000,
      ubicacion: "Bogotá",
      area: "300 m2",
      detalles:
        "Local en centro financiero con alto flujo de empresas y clientes corporativos.",
    },
    {
      nombre: "Terreno para Proyecto Agrícola",
      categoria: "Terreno",
      imagen: "terreno_proyecto_agricola.jpg",
      codigo: 1038,
      precio: 1000000000,
      ubicacion: "Valle del Cauca",
      area: "100 ha",
      detalles:
        "Terreno con suelo fértil y agua para proyecto agrícola de cultivos especiales.",
    },
    {
      nombre: "Casa con Piscina y Jacuzzi",
      categoria: "Casa",
      imagen: "casa_piscina_jacuzzi.jpg",
      codigo: 1039,
      precio: 800000000,
      ubicacion: "Cali",
      area: "220 m2",
      detalles:
        "Casa con piscina climatizada, jacuzzi y zona de BBQ, ideal para entretenimiento.",
    },
    {
      nombre: "Apartamento Amoblado",
      categoria: "Apartamento",
      imagen: "apartamento_amoblado.jpg",
      codigo: 1040,
      precio: 500000000,
      ubicacion: "Bogotá",
      area: "100 m2",
      detalles:
        "Apartamento totalmente amoblado con estilo moderno y electrodomésticos de alta gama.",
    },
    {
      nombre: "Finca de Cacao",
      categoria: "Finca",
      imagen: "finca_cacao.jpg",
      codigo: 1041,
      precio: 1800000000,
      ubicacion: "Nariño",
      area: "150 ha",
      detalles:
        "Finca productiva con cultivos de cacao y infraestructura para procesamiento.",
    },
    {
      nombre: "Edificio de Apartamentos con Piscina",
      categoria: "Edificio",
      imagen: "edificio_apartamentos_piscina.jpg",
      codigo: 1042,
      precio: 12000000000,
      ubicacion: "Barranquilla",
      area: "6000 m2",
      detalles:
        "Edificio residencial con amplias áreas comunes, piscina, gimnasio y zona de recreación.",
    },
    {
      nombre: "Local en Zona Gastronómica",
      categoria: "Local",
      imagen: "local_zona_gastronomica.jpg",
      codigo: 1043,
      precio: 700000000,
      ubicacion: "Medellín",
      area: "150 m2",
      detalles:
        "Local en zona de restaurantes y cafeterías, con alta demanda gastronómica.",
    },
    {
      nombre: "Terreno con Vista a la Montaña",
      categoria: "Terreno",
      imagen: "terreno_vista_montana.jpg",
      codigo: 1044,
      precio: 400000000,
      ubicacion: "Antioquia",
      area: "3000 m2",
      detalles:
        "Terreno con vista panorámica a la montaña, ideal para construcción de cabañas o residencia.",
    },
    {
      nombre: "Casa de Diseñador",
      categoria: "Casa",
      imagen: "casa_disenador.jpg",
      codigo: 1045,
      precio: 1200000000,
      ubicacion: "Bogotá",
      area: "400 m2",
      detalles:
        "Casa diseñada por arquitecto reconocido, con acabados exclusivos y tecnología de punta.",
    },
    {
      nombre: "Apartamento con Jardín Privado",
      categoria: "Apartamento",
      imagen: "apartamento_jardin_privado.jpg",
      codigo: 1046,
      precio: 750000000,
      ubicacion: "Medellín",
      area: "200 m2",
      detalles:
        "Apartamento con amplio jardín privado, terraza y áreas verdes comunes.",
    },
    {
      nombre: "Finca Ganadera y Agrícola",
      categoria: "Finca",
      imagen: "finca_ganadera_agricola.jpg",
      codigo: 1047,
      precio: 2500000000,
      ubicacion: "Meta",
      area: "500 ha",
      detalles:
        "Finca productiva con cultivos agrícolas, pastizales y áreas para ganado.",
    },
    {
      nombre: "Villa del Sol",
      categoria: "Casa",
      imagen: "villa_del_sol.jpg",
      codigo: 1001,
      precio: 120000000,
      ubicacion: "Medellín",
      area: "150 m2",
      detalles:
        "Hermosa casa de estilo moderno con amplias habitaciones y jardín privado.",
    },
    {
      nombre: "Piso Ejecutivo",
      categoria: "Apartamento",
      imagen: "piso_ejecutivo.jpg",
      codigo: 1002,
      precio: 350000000,
      ubicacion: "Bogotá",
      area: "120 m2",
      detalles:
        "Elegante apartamento con vistas panorámicas, ubicado en una zona exclusiva de la ciudad.",
    },
    {
      nombre: "Casa de Campo",
      categoria: "Finca",
      imagen: "casa_de_campo.jpg",
      codigo: 1003,
      precio: 500000000,
      ubicacion: "Eje Cafetero",
      area: "300 m2",
      detalles:
        "Finca con amplias zonas verdes, piscina y espacios ideales para el descanso y la recreación familiar.",
    },
    {
      nombre: "Oficina Ejecutiva",
      categoria: "Oficina",
      imagen: "oficina_ejecutiva.jpg",
      codigo: 1004,
      precio: $250000000,
      ubicacion: "Cali",
      area: "80 m2",
      detalles:
        "Oficina moderna y funcional, ideal para empresas en crecimiento.",
    },
    {
      nombre: "Apartamento en Playa",
      categoria: "Apartamento",
      imagen: "apartamento_playa.jpg",
      codigo: 1005,
      precio: $700000000,
      ubicacion: "Cartagena",
      area: "200 m2",
      detalles:
        "Apartamento frente al mar con acceso directo a la playa y terraza privada.",
    },
    {
      nombre: "Local Comercial",
      categoria: "Local",
      imagen: "local_comercial.jpg",
      codigo: 1006,
      precio: 180000000,
      ubicacion: "Barranquilla",
      area: "100 m2",
      detalles:
        "Local con excelente visibilidad y ubicación estratégica para negocios.",
    },
    {
      nombre: "Terreno en Desarrollo",
      categoria: "Terreno",
      imagen: "terreno_desarrollo.jpg",
      codigo: 1007,
      precio: 300000000,
      ubicacion: "Pereira",
      area: "500 m2",
      detalles:
        "Terreno con potencial para desarrollo residencial o comercial, cerca de importantes vías de acceso.",
    },
    {
      nombre: "Apartamento con Vistas a la Ciudad",
      categoria: "Apartamento",
      imagen: "apartamento_vistas_ciudad.jpg",
      codigo: 1048,
      precio: 650000000,
      ubicacion: "Bogotá",
      area: "180 m2",
      detalles:
        "Apartamento con amplias ventanas y vistas panorámicas a la ciudad, en zona residencial tranquila.",
    },
    {
      nombre: "Terreno en Zona Industrial",
      categoria: "Terreno",
      imagen: "terreno_zona_industrial.jpg",
      codigo: 1049,
      precio: 1000000000,
      ubicacion: "Medellín",
      area: "2000 m2",
      detalles:
        "Terreno en zona industrial con acceso a vías principales y servicios básicos para desarrollo empresarial.",
    },
  ],
};
